# Site settings
title: heroxiao个人前端博客
header-img: "img/autumn2.jpg"
tagline: ""
description: "没有钱，你拿什么来维持你的亲情，稳定你的爱情，联络你的友情，靠嘴吗？别闹了，大家都挺忙的"
baseurl: ""
#url: "http://azeril.me"
#url: "http://localhost:4000"
host:             0.0.0.0
port:             9002
encoding:         UTF-8

# About/contact
owner: 
  name: "heroxiao"
  email: heroxiao73@outlook.com
  bio: ""

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

github_username: heroazure

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Final-Cut-Pro-X-Shortcuts.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: heroxiao/杭州

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "heroxiao"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : heroxiao
  disqus :
      short_name : heroxiao

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation